sonar.projectKey=sonarcloudpydemo
sonar.organization=Sonarclouddemo
sonar.projectName=node-demo
sonar.sources=.
sonar.test.inclusions=**/*.test.js,**/*.spec.js

# Path to the generated LCOV file
sonar.javascript.lcov.reportPaths=coverage/lcov.info
