# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: SonarQube Code Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  sonarcloud:
    name: Test and Analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Shallow clones must be disabled for a better relevancy of analysis

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20.x'
          #cache: 'npm'
          #cache-dependency-path: 'package-lock.json'

      - name: Install Dependencies
        run: npm install
        #run: npm ci

      - name: Run Tests and Generate Coverage
        run: npm run test:coverage

      - name: Run SonarQube Scan
        uses: sonarsource/sonarcloud-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Install jq via powershell
        shell: powershell
        run: |
          # 1. Query the official GitHub API endpoint for jq releases
          $response = Invoke-RestMethod -Uri "https://github.com"
          
          # 2. Filter the assets for the Windows 64-bit executable and expand the download URL
          $latestUrl = $response.assets | Where-Object { $_.name -like "*win64.exe" } | Select-Object -ExpandProperty browser_download_url
          
          Write-Host "Found latest jq download URL: $latestUrl"
          
          # 3. Download the executable to the runner's temporary directory
          Invoke-WebRequest -Uri $latestUrl -OutFile "$env:RUNNER_TEMP\jq.exe"
          
          # 4. Add the temporary directory to the GitHub Actions PATH environment variable
          Add-Content -Path $env:GITHUB_PATH -Value "$env:RUNNER_TEMP"

      - name: Enforce SonarQube Quality Gate
        uses: sonarsource/sonarcloud-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  # 2. Wait for the Quality Gate to compute (Forces the pipeline to sync)
      - name: Wait for Sonar Quality Gate
        uses: SonarSource/sonarqube-quality-gate-action@v1
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          #SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # 3. Request report metrics using the Web API
      - name: Download Sonar Quality Report
        run: |
          curl -s -u "${{ secrets.SONAR_TOKEN }}:" \
            "${{ secrets.SONAR_HOST_URL }}/api/measures/component?component=sonarcloudpydemo&metricKeys=bugs,vulnerabilities,code_smells,coverage,duplicated_lines_density" \
            -o sonar-report.json
           
      # 4. Save the downloaded report to your GitHub Actions run
      - name: Upload Report Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sonar-quality-report
          path: sonar-report.json
